@hostname = http://127.0.0.1
@port = 3000
@singleBookId = 22

### Get all books
GET {{hostname}}:{{port}}/books/ HTTP/1.1

### Get single book
GET {{hostname}}:{{port}}/books/{{singleBookId}}/ HTTP/1.1

### Create book
POST {{hostname}}:{{port}}/books/ HTTP/1.1
Content-Type: application/json

{
    "id": "4",
    "title": "Портрет Дориана Грея",
    "author": "Оскар Уайльд"
}